Document: tomahawk
Title: Debian tomahawk Manual
Author: <insert document author here>
Abstract: This manual describes what tomahawk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tomahawk/tomahawk.sgml.gz

Format: postscript
Files: /usr/share/doc/tomahawk/tomahawk.ps.gz

Format: text
Files: /usr/share/doc/tomahawk/tomahawk.text.gz

Format: HTML
Index: /usr/share/doc/tomahawk/html/index.html
Files: /usr/share/doc/tomahawk/html/*.html
